server:
  port: 9191

spring:
  application:
     name: JOBPORTAL2
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/jobportal
    username: root
    password: myadmin
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
